name: Master - Clean Assemble and Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Delete package
        uses: jackhowa/delete-github-package-versions@v0.4.9
        with:
          version-pattern: "2.0.3" # The regex needs to be escaped!
          names: |
            com.chinalwb.libraries.droidlib

      
