# This is a basic workflow to help you get started with Actions

name: Test step output

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

        
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: get output
        id: step1
        run: echo "::set-output name=id::2"
      - id: step2
        run: echo ${{steps.step1.outputs.test}}
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

